# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: missile_attack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14missile_attack.proto\x12\x0emissile_attack\"\x14\n\x07Request\x12\t\n\x01M\x18\x01 \x01(\x05\"0\n\x08Response\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0e\n\x06radius\x18\x03 \x01(\x05\x32\x45\n\x06\x41ttack\x12;\n\x06\x61ssign\x12\x17.missile_attack.Request\x1a\x18.missile_attack.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'missile_attack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=60
  _globals['_RESPONSE']._serialized_start=62
  _globals['_RESPONSE']._serialized_end=110
  _globals['_ATTACK']._serialized_start=112
  _globals['_ATTACK']._serialized_end=181
# @@protoc_insertion_point(module_scope)
