# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import missile_attack_pb2 as missile__attack__pb2


class AttackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.assign = channel.unary_unary(
                '/missile_attack.Attack/assign',
                request_serializer=missile__attack__pb2.Request.SerializeToString,
                response_deserializer=missile__attack__pb2.Response.FromString,
                )


class AttackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def assign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'assign': grpc.unary_unary_rpc_method_handler(
                    servicer.assign,
                    request_deserializer=missile__attack__pb2.Request.FromString,
                    response_serializer=missile__attack__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'missile_attack.Attack', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Attack(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def assign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/missile_attack.Attack/assign',
            missile__attack__pb2.Request.SerializeToString,
            missile__attack__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
